
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xexample.h"

/*
* The configuration table for devices
*/

XExample_Config XExample_ConfigTable[XPAR_XEXAMPLE_NUM_INSTANCES] =
{
	{
		XPAR_EXAMPLE_0_DEVICE_ID,
		XPAR_EXAMPLE_0_S_AXI_AXI_CPU_BASEADDR
	}
};


